[devshell]
name = "basedapi"

# Message Of The Day (MOTD) is displayed when entering the environment with an
# interactive shell. By default it will show the project name.
#
motd = "To get starded, run `nix build .#`, then run the api with `python ./result/"

# Add packages from nixpkgs here. Use `nix search nixpkgs <term>` to find the
# package that you need.
#
# NOTE: don't forget to put commas between items! :)
packages = [
  "python3",
]

# Declare commands that are available in the environment.
[[commands]]
help = "Run the api"
name = "run"
command = "nix run .# 2>/dev/null || nix run github:rpgwaiter/basedapi"

[[commands]]
package = "nixpkgs-fmt"
category = "formatters"

[[commands]]
help = "github utility"
name = "hub"
package = "gitAndTools.hub"
category = "utilites"

# [[commands]]
# help = "golang linter"
# package = "golangci-lint"
# category = "linters"