[devshell]
name = "basedapi"

# Message Of The Day (MOTD) is displayed when entering the environment with an
# interactive shell. By default it will show the project name.
#
# motd = ""

# Add packages from nixpkgs here. Use `nix search nixpkgs <term>` to find the
# package that you need.
#
# NOTE: don't forget to put commas between items! :)
packages = [
  "ffmpeg",
  "python3",
  "python3Packages.pymediainfo",
]

# Declare commands that are available in the environment.
[[commands]]
help = "Run the api"
name = "dev"
command = "(nix build .# || nix build github:rpgwaiter/basedapi) && python ./result/lib/python3.9/site-packages/basedapi.py"

[[commands]]
package = "nixpkgs-fmt"
category = "formatters"

[[commands]]
help = "github utility"
name = "hub"
package = "gitAndTools.hub"
category = "utilites"

# [[commands]]
# help = "golang linter"
# package = "golangci-lint"
# category = "linters"